#!/usr/bin/env python

import sys

from rqt_action_launcher.action_launcher import ActionLauncher
from rqt_gui.main import Main

plugin = 'rqt_action_launcher'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))